#!/usr/bin/env bash
# a Bash script

touch /var/run/myscript.pid
echo $$ > /var/run/myscript.pid

while true ;
do
    echo "To infinity and beyond"
    sleep 2
    trap "echo I hate the kill command" 15
    trap "echo Y U no love me?!" 2
    trap 'rm /var/run/myscript.pid && kill $$' 3, 15
done
