#!/usr/bin/env bash
# a Bash script that loops from 1 to 10 and:
# displays bad luck for the 4th loop iteration
# displays good luck for the 8th loop iteration
# displays Best School for the other iterations

var=1

while [ $var -lt 21 ];
do
    if [ $var = 4 ]
    then
	echo $var
	echo "bad luck from China"
    elif [ $var = 9 ]
    then
	echo $var
	echo "bad luck from Japan"
    elif [ $var = 17 ]
    then
	echo $var
	echo "bad luck from Italy"
    else
	echo $var
    fi
    var=$((var + 1))
done
