#!/usr/bin/env bash
# a Bash script that loops from 1 to 10 and:
# displays bad luck for the 4th loop iteration
# displays good luck for the 8th loop iteration
# displays Best School for the other iterations

var=1

while [ $var -lt 21 ];
do
    case $var in
	"4")
   	echo $var
	echo "bad luck from China"
	var=$((var + 1))
	;;
	"9")
	echo $var
	echo "bad luck from Japan"
	var=$((var + 1))
	;;
	"17")
	echo $var
	echo "bad luck from Italy"
	var=$((var + 1))
	;;
    esac
	echo $var
	var=$((var + 1))
done
