#!/usr/bin/env bash
# a Bash script that displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59

hours=0

while [ $hours -le 12 ]
do
    min=1
    echo -n "Hour:"
    echo $hours
    while [ $min -le 59 ]
    do
	  echo $min
	  min=$((min + 1))
    done
    hours=$((hours + 1))
done
