#!/usr/bin/env bash
# a Bash script that displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed

var="$(ls)"
for elt in $var;
do
    echo "${elt}" | cut -d '-' -f 2-
done
