#!/usr/bin/env bash
# a bash script that that configures an Ubuntu server requirements.

cp /etc/hosts ~/hosts.new
echo "127.0.0.2        localhost" > ~/hosts.new
echo "8.8.8.8        facebook.com" > ~/hosts.new
cp --force ~/hosts.new /etc/hosts
